line-length = 100
target-version = "py312"
extend-exclude = [
    "tasks/*/assets/dataset/*/files/",
    "tasks/*/assets/library/*/sources/",
]

[lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "SIM",    # flake8-simplify
    "I",      # isort
    "TID252", # no relative imports
]

[lint.isort]
known-first-party = ["arf", "tasks"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"
